### ISSUE TITLE
Sector Cache ignores cache-line size config option

### ISSUE THREAD

**Issue by barnes88** [accel-sim/accel-sim-framework#137]
The sector cache uses hard-coded values for sector size (32B) and number of sectors (4), there is no indication in the config files that the line-size parameter is not used for sectored L1D.

https://github.com/accel-sim/gpgpu-sim_distribution/blob/dev/src/abstract_hardware_model.h#L762
https://github.com/accel-sim/gpgpu-sim_distribution/blob/dev/src/gpgpu-sim/gpu-cache.h#L675

**Comment by FJShen** [comment]
Direction of development (as of June 12 2023):

The fix we've decided to do is to disable cacheline size configurations for sector cache. If a simulation attempts to use sector cache with a non-default sector size, the simulation will abort with error message. 

The reason is that we haven't seen a need to change sector cache's sector size (default 32 B) and cacheline size (default 128 B); furthermore, we haven't seen evidence Nvidia's lineup of GPGPUs up till Ampere A100 has changed those sector cache parameters. We're currently unsure if Hopper H100 is using a different sector cache configuration. AMD GPGPUs use a different warp size, so a different sector cache size could and should be considered, but we currently do not support this. 

A deeper cause for postponing "arbitrary" sector cache configurability is the sector size is closely related to GPU memory access coalescing, and changing the sector cache size wouldn't make much sense performance-wise unless the coalescing logic is changed accordingly. At this point we do not support configurable coalescing logic. 

** disregard everything below (notes before Jun 12, 2023)

The sector cache is currently used by some popular gpu models like QV100, and the per-sector states of each cache line are all implemented as C-style arrays with hard coded sizes. I plan to replace those arrays with dynamically allocated arrays. To save space, avoid storing the sector size and sector count in each cache line object. That is unnecessary overhead (this is also why std::vector is not the best solution). Instead, i will store the sector size info in the owner of these cache line objects, ie the cache object.  

A second step is to add sector size to the cache configuration string. The user will supply sector size and line size. The sector chunk size (i.e. how many sectors per line) will be inferred. Better sanity check cacheline size is not larger than 

Replace all use of operator[] to read bits of the bitset with dynamic_bitset::test(). This allows assertion test.
 be changed. The MAX_MEMORY_ACCESS_SIZE is 128, equal to the current hard-coded cacheline size.

Boost software license need to be added to source code.

`mem_access_sector_mask` is relevant to the sector chunk size (how many sectors in one cache line), `mem_access_byte_mask_t` is relevant to the `MAX_MEMORY_ACCESS_SIZE`. Both may need to be modified. But not all occurrences of them need to be changed to accommodate the use of configurable sector cache. For example, global memory access coalescing (implemented in `warp_inst_t::memory_coalescing_arch`) generates 32, 64, or 128 bytes accesses to the memory, the granularity is 32 bytes and the max access size is 128 bytes. That's why you see a lot of hard-coded numbers like 1, 2, 4, 32, 64, 128 in `warp_inst_t::memory_coalescing_arch_reduce_and_send`. I think there's no need to disturb these numbers just to accommodate configurable sector cache.

For now, I'll disallow the L1 and L2 caches to have different sector sizes - it's okay if any of them is a non-sector cache, but in the case both are sector caches, they must have the same sector size. This will simplify the implementation of function `memory_sub_partition::breakdown_request_to_sector_requests(mem_fetch *mf)` .

With the `mem_access_sector_mask_t` being aliased to a `boost::dynamic_bitset`, how memory accesses are handled / coalesced need to be updated as well.  A preliminary study of code suggests that at least the following functions need to be changed:

- `gpgpu_sim::perf_memcpy_to_gpu`
- `warp_inst_t::memory_coalescing_arch` 
- `warp_inst_t::memory_coalescing_arch_atomic` 
- `warp_inst_t::memory_coalescing_arch_reduce_and_send` 

The definition of `struct transaction_info` need to be changed. 

`typedef std::bitset<MAX_MEMORY_ACCESS_SIZE> mem_access_byte_mask_t` also need to
