### ISSUE TITLE
what is the difference between accelwattch_ptx_sim.xml and accelwattch_ptx_sim_alt.xml

### ISSUE THREAD

**Issue by MWHYNOT** [accel-sim/accel-sim-framework#141]
excuse me, i have a question that what is the difference between accelwattch_ptx_sim.xml and accelwattch_ptx_sim_alt.xml in gpgpu-sim_distribution/configs/tested-cfgs/SM7_QV100/

**Comment by MWHYNOT** [comment]
Thanks in advance

**Comment by JRPan** [comment]
@VijayKandiah

**Comment by VijayKandiah** [comment]
Hi, please look at section 5.4 of our MICRO21 Paper. 

" We use two different starting points for the scaling factors used in the initial iteration of this process. For one of the starting points, all initial scaling factors are set to one, thus there is no scaling taking place initially. The other starting point is obtained from the GPUWattch model for NVIDIA Fermi GTX 480 which has been independently validated.
Due to having two starting points, we end up with two AccelWattch models. 
The model obtained from the Fermi starting point achieves higher accuracy (9.2% vs. 14.8% MAPE on the validation set for SASS SIM).
Thus, for each AccelWattch variant, we adopt the model obtained from the Fermi starting point as the final AccelWattch model (`accelwattch_ptx_sim.xml`). "

We include as `accelwattch_ptx_sim_alt.xml`, the other model obtained from setting all initial scaling factors to one. For all practical purposes, please use the `accelwattch_ptx_sim.xml` because it has higher accuracy in comparison to `accelwattch_ptx_sim_alt.xml`.

**Comment by JRPan** [comment]
Thanks Vijay!
