### ISSUE TITLE
Inst LD with mask 00000000 triggers assertion error

### ISSUE THREAD

**Issue by gty111** [accel-sim/accel-sim-framework#152]
When simulating a program, I met some insts like `c3c0 00000000 1 R28 LD.E.64 1 R24 8 1 0x0 0 ` .  I found accel sim also not set `type of space` for these insts so it triggered assertion error just like #150 . I looked through trace_driven.cc and found that when meeting LD with mask 00000000 it will enter this [statement](https://github.com/accel-sim/accel-sim-framework/blob/release/gpu-simulator/trace-driven/trace_driven.cc#L332). But due to the mask being all zero, it didn't set the type of space. I want to know what is the meaning of a LD inst with mask all zero. And any idea to fix that? Thanks.

**Comment by JRPan** [comment]
Can you share the entire trace? Each bit in the mask indicates whether the inst is simulated by the thread (total 32 bits, because 1 warp has 32 threads). I want to make sure if the inst is indeed not executed or if there is a bug in the tracer.

if the tracer is correct, then this should be a corner case bug that we should fix. 

Thanks,
JR

**Comment by gty111** [comment]
You can find traces at [here](https://github.com/gty111/Share/blob/main/31_basic_syrk_trace.tar.gz). Or generate from [cutlass(-DCUTLASS_NVCC_ARCHS=80)](https://github.com/NVIDIA/cutlass/tree/v2.10.0/examples/31_basic_syrk) with args `512 512`.

**Comment by JRPan** [comment]
The tracer records the first active thread's address, and the rest is offset from that address. For example:
`c190 ffffffff 1 R36 LDS.128 1 R36 16 2 0x1000 16 16 16 16 16 16 16 32 -16 48 -16 48 -16 48 -16 64 16 -48 16 80 16 -48 16 96 -16 -16 -16 112 -16 -16 -16`
The mask is `ffffffff`, which indicates all 32 threads are active in this warp. Thread 0 loads from `0x1000`, and thread 1 loads from `0x1000 + 16`, and so on. There are several modes.  You can check tracer_tool.cu if you want.

In your case, no thread is active in the warp. So there is no address because there is no load executed. Thus the address is just `0x0`. This should be easy to fix. Simply finding a way to bypass the assertion should work. Feel free to submit a PR if you want. 

Thanks,
JR

**Comment by gty111** [comment]
Thanks for the explannation. After checking the [code](https://github.com/accel-sim/gpgpu-sim_distribution/blob/dev/src/abstract_hardware_model.cc#L289), I find that it will check the mask and when the mask is zero it will simply return. So that inst won't trigger assterion failure. Maybe I'm confused. Sorry for that.
