### ISSUE TITLE
Some minor bugs I found

### ISSUE THREAD

**Issue by JRPan** [accel-sim/accel-sim-framework#17]
# __tracer_nvbit__ only make on dev branch but not release branch. #
error below when making on release:
```
g++ -o post-traces-processing post-traces-processing.cpp
post-traces-processing.cpp:13:23: error: ‘>>’ should be ‘> >’ within a nested template argument list
   vector<vector<string>> warp_insts_array;
                       ^
Makefile:4: recipe for target 'post-traces-processing' failed
make[1]: *** [post-traces-processing] Error 1
```
# Path mismatch between python scripts inside  ./util #
output folder generated by run_simulation.py: `./sim_run_11.0/bfs-rodinia-2.0-ft/__data_graph4096_txt___data_graph4096_result_txt/QV100-SASS`

get_stats.py is looking for: `./sim_run_11.0/bfs-rodinia-2.0-ft/__args______data_graph4096_txt___data_graph4096_result_txt____accel_sim_mem____1G__/QV100-SASS `

It seems plot_correlation.py also has issue with finding the results. Also, it says plots are generated successfully while files are not there. Still looking into this. Outputs are shown below:
```
 ./util/plotting/plot-correlation.py -c per.kernel.stats.csv -H ./hw_run/device-0/11.0/
-----------------------------------------------------------------
All Card Summary:
HW Summary for Tesla V100-SXM2-32GB [Contains 1 Apps]:
----------------------------------------------------------------


Output Available at: file:<some-path>/accel-sim-framework/util/plotting/correl-html
```

**Comment by mkhairy** [comment]
The first error seems because of compilation compatibility. I am able to compile successfully on gcc  7.5.
Also, the line the error is referring to is the same in the dev and release branches which is weird that has an error in one and not in the other!
Dev:
https://github.com/accel-sim/accel-sim-framework/blob/a40480bdd2dba714f5f0da4a0295faf6c2758f54/util/tracer_nvbit/tracer_tool/traces-processing/post-traces-processing.cpp#L13

Release:
https://github.com/accel-sim/accel-sim-framework/blob/21fdb684796bba6057a45eeb6429b04cc7577537/util/tracer_nvbit/tracer_tool/traces-processing/post-traces-processing.cpp#L13

**Comment by mkhairy** [comment]
For the second error, I think this is because you run the simulation in the release branch and this created the results in the above directory, then you moved to dev branch and tried to collects stats and do correlation while the results are still using old directory. So, be consistent in this. If you rerun the simulation in the dev branch again and collect stats, I think the issue will be resolved.  Please, let us know if this helps or you have further issues on this.

@tgrogers please confirm?

**Comment by JRPan** [comment]
Thank you. I started all over with the release branch. It worked.
