### ISSUE TITLE
PTX Sim Segmentation Fault

### ISSUE THREAD

**Issue by huydinhtran** [accel-sim/accel-sim-framework#181]
Hi,

I'm following the instruction from the "MICRO'21 Artifact Appendix Manual". SASS simulations ran fine but all of the PTX runs got segmentation faults. What are some potential causes for this?

**Comment by JRPan** [comment]
What branch are you using? 
Does running without Accel-Wattach work? Can you try launching tasks using the Accel-Sim readme without the power model? 

Or it would be great if you could gdb to see the position of the segmentation fault

Thanks.

**Comment by huydinhtran** [comment]
I was using the old "release-accelwattch" branch. Somehow remaking gpgpu-sim fixed the problems. Also, how do you get the right config of your GPU for the config file of gpgpu-sim? I'm using a Pascal GTX 1050Ti.

**Comment by JRPan** [comment]
We have an issue that Makefile does not track changed files correctly. So that's probably what you had, and a completely clean build fixed it. 

You can create new configs by modifying an existing one with the same architecture. For your case, you can start with SM6_TITANX. Changing the SM count, memory bandwidth, and L2 should be enough. You don't need to change anything SM level.
Alternatively, you can use the tuner under `/util`. It queries the GPU info and uses that with micro benchmarks to create a config for you. 

The best would be to generate one with the tuner and then cross-reference it with the existing config to do a sanity check. 

Thanks
