### ISSUE TITLE
Are there any chances to reduce the memory usage?

### ISSUE THREAD

**Issue by allencho1222** [accel-sim/accel-sim-framework#27]
While accelsim reduces memory usage by deleting the object, `warp`,

it is still hard to run multiple simulations if one of them contains traces that require a large amount of memory, such as SSSP or MST in lonestar and DeepBench (These kills other simulations due to memory capacity).

I think that this is because the memory usage of instructions from the current issued thread block (`threadblock_traces`).

Can I make sure that removing instructions done for all warps in the thread thread block from the vector does not harm simulations?

If my assumption is not correct, could you tell me what causes a large amount of memory usage?

**Comment by mkhairy** [comment]
Hi, sorry for my late reply. Yes your assumption is correct. The remaining high memory usage is because we load all the instructions of the active threadblock in a string format to the memory. Your optimization is correct and should work but not sure how to implement 
that as c++ vector is contiguous memory array. You may need to use different data structure (deque for example). In fact, a better optimzaion would be loading only a block of instructions into memory for each active warp, and after they are executed, ww can load the next instructions and so on, rather than loading everything to the memory as we do right now. However this will need multiple readers and seek capablity  in the traces file. This is Something that is on our plan but has not done yet. Please let us know if you do any memory optimization, so you can PR this to our repo and I will review and accept that.
