### ISSUE TITLE
Assertion when tracing ampere traces with copy async

### ISSUE THREAD

**Issue by mkhairy** [accel-sim/accel-sim-framework#46]
The assertion place:
https://github.com/accel-sim/accel-sim-framework/blob/4c2bf09a79d6b57bb10fe1898700930a5dd5531f/util/tracer_nvbit/tracer_tool/tracer_tool.cu#L174

The LDGSTS inst is not supported yet. We need to update the tracer, and the model to execute copy async

**Comment by mahmoodn** [comment]
Assuming LDSGST [X], [Y] means sh_mem[x] <-- gl_mem[y], the instruction has two parts: 
1) LDGSTS [R12], ... which acts like a store instructions. So this section
```
      else if (instr->getNumOperands() > 0 &&
               instr->getOperand(0)->type == InstrType::OperandType::MREF) {
        src_oprd[0] = instr->getOperand(0)->u.mref.ra_num;
        mem_oper_idx = 0;
        srcNum++;     // ***
      } 
```
uses the register no. 12 as the address for first operand (src_oprd[0])

2) LDGSTS ...., [R13] ... which acts like a load instruction. So this section 
```
      for (int i = 1; i < MAX_SRC; i++) {
        if (i < instr->getNumOperands()) {
          const InstrType::operand_t *op = instr->getOperand(i);
          if (op->type == InstrType::OperandType::MREF) {
            // mem is found
            assert(srcNum < MAX_SRC);
            src_oprd[srcNum] = instr->getOperand(i)->u.mref.ra_num;  // for ldgsts srcNum is now 1 because it had been incremented at ***
            srcNum++;
            mem_oper_idx++;
            if (instr->getOperand(0)->type == InstrType::OperandType::MREF) { // First op is MREF
              // src_oprd[0] holds the address for the store
              // src_oprd[1] holds the address for the load
              mem_oper_idx = 2;
           }
```
starts from the second operand and see that is a MREF and (src_oprd[1]).

So, for store instructions we have
  - mem_oper_idx = 0;
  - srcNum = 1;
  - src_oprd[0]   (memory address)

For load instructions we have
  - mem_oper_idx = 0;
  - srcNum = 1;
  - src_oprd[0]   (memory address)

For LDGSTS we have
  - mem_oper_idx = 2;
  - srcNum = 2;
  - src_oprd[0]  and src_oprd[1] 

At this point it is safe to ignore the `assert` because for LDGSTS, when the `for` terminates, `mem_oper_inx` is 2. While the name implies about memory operand index, the value of 2 here means that it has incremented two times.

Now, this section
```
      /* mem addresses info */
      if (mem_oper_idx >= 0) {
        nvbit_add_call_arg_const_val32(instr, 1);
        nvbit_add_call_arg_mref_addr64(instr, 0);
        nvbit_add_call_arg_const_val32(instr, (int)instr->getSize());
      } else {
        nvbit_add_call_arg_const_val32(instr, 0);
        nvbit_add_call_arg_const_val64(instr, -1);
        nvbit_add_call_arg_const_val32(instr, -1);
      }
```
Should be changed like below
```
      /* mem addresses info */
      if (mem_oper_idx >= 0 and mem_oper_idx < 2) { // LOAD or STORE
        nvbit_add_call_arg_const_val32(instr, 1);
        nvbit_add_call_arg_mref_addr64(instr, 0);
        nvbit_add_call_arg_const_val32(instr, (int)instr->getSize());
      } else if (mem_oper_idx == 2) { // LDGSTS
        nvbit_add_call_arg_mref_addr64(instr, 1);
        nvbit_add_call_arg_mref_addr64(instr, 0);
        nvbit_add_call_arg_const_val32(instr, (int)instr->getSize());
      } else {
        nvbit_add_call_arg_const_val32(instr, 0);
        nvbit_add_call_arg_const_val64(instr, -1);
        nvbit_add_call_arg_const_val32(instr, -1);
      }
```


I am not sure about nvbit_add_call_arg* because I don't understand what does `nvbit_add_call_arg_const_val32(instr, 1);` mean. In the nvbit code, that is related to opcode. I would like to know if I made those changes, how can I verify that the tracer successfully traces that instruction? How did you do that for other instructions like store and load?

**Comment by JRPan** [comment]
related: #86
