### ISSUE TITLE
Question about trace format

### ISSUE THREAD

**Issue by mahmoodn** [accel-sim/accel-sim-framework#5]
Hi and thanks for the tool.
I would like to know if there is any information about the trace format which I see as below

```
#traces format = threadblock_x threadblock_y threadblock_z warpid_tb PC mask dest_num [reg_dests] opcode src_num [reg_srcs] mem_width [adrrescompress?] [mem_addresses]

31 0 0 3 0000 ffffffff 1 R1 IMAD.MOV.U32 2 R255 R255 0
102 0 0 2 0000 ffffffff 1 R1 IMAD.MOV.U32 2 R255 R255 0
```
What is that `mask`?
Also, since some columns are optional (those with `[]`), I want to know how can we can correctly map the columns? For example, in the format there are 14 columns, but in the lines below that, I see 13 columns.

**Comment by mkhairy** [comment]
Hi, thanks for your interest in our tool.

the mask is the active mask of the warp during the execution, i.e. which threads are active during the instruction. They are represented in hex format. "ffffffff" means all the 32 threads in the mask are active.

in the example, you mentioned, all the format columns are presented except the addresses, so that's why there are 13 columns.

 For more explanation, the first instruction you listed above is interpreted is as following

threadblock_x threadblock_y threadblock_z=31 0 0
warpid_tb=3
PC =0000  (hexa)
mask=ffffffff  (hexa)
dest_num=1 (how many destination registers) 
[reg_dests]=R1 (if dest_num=0, then this would be empty)
opcode=IMAD.MOV.U32
src_num=2
[reg_srcs]=R255 R255
mem_width = 0 (if mem_width>0, then there will be some addresses listed afterwards)

I hope this helps, let me know if you have further questions.

**Comment by mahmoodn** [comment]
Thanks for the explanation. Regarding the format, I want to know what is the rule? For example, the following line has 11 columns

```
142 0 0 5 0040 ffffffff 1 R3 S2R 0 0
```
There may be other lines with different number of columns. I want to know what is the rule to interpret that?

**Comment by mkhairy** [comment]
Any column is NOT contained in brackets [] must exist in any instruction format, so any instruction should have at least 10 column entries which they are 

```
#traces format = threadblock_x threadblock_y threadblock_z warpid_tb PC mask dest_num opcode src_num mem_width
```

The other columns that are in brackets [] may or may not exist based on the instruction characteristics, for example:
"dest_num" tells us the number of destination registers.
 If dest_num=0, then [reg_dests] will be empty and not exist in the trace.
 If dest_num>0, this means that this instruction has dest_num destination registers, the [reg_dests] will list these registers values.

Similarly,  the src_num and [reg_srcs].

Finally, the mem_width rule is as following:
If mem_width=0, this implies that it is not a memory instruction and [adrrescompress?] [mem_addresses] will be empty.
if mem_width>0,  this implies that this is a memory instruction with mem_width as the memory width of the data to be loaded per thread, and  [adrrescompress?] [mem_addresses] will list the memory addresses in a compressed format. 

For, more information, I would highly encourage you to read the tracer code that generates these traces [here ](https://github.com/accel-sim/accel-sim-framework/blob/c6d296276268e2ad947eb55f929c587fee04e37a/util/tracer_nvbit/tracer_tool/tracer_tool.cu#L521)

**Comment by mahmoodn** [comment]
OK. Thank you very much.
