### ISSUE TITLE
Error when running simulation on the RTX2060

### ISSUE THREAD

**Issue by Rutsow** [accel-sim/accel-sim-framework#78]
I have almost tested the l1_bw_32f benchmark on all the simulation configs. However, for the RTX2060,  in the file l1_bw_32f-NO_ARGS.accelsim-commit-modified_0.0.exx, it shows me:

GPGPU-SIM ** ERROR: Unknown Option: '-gpugpu_shmem_option'

Additionally, I didn't find this option in other config files, except RTX2060.

How can I run the simulation on the RTX2060 config?

**Comment by JRPan** [comment]
Hi, 


Which commit you are on for both Accel-Sim and GPGPU-sim?
The option is parsed here [gpgpu-sim/gpu-sim.cc](https://github.com/accel-sim/gpgpu-sim_distribution/blob/dev/src/gpgpu-sim/gpu-sim.cc#L331)
This option is currently still in the dev branch and only available under the [accel-sim's fork of gpgpu-sim](https://github.com/accel-sim/gpgpu-sim_distribution). Assuming you are using the dev version of Accel-Sim, please try pulling the latest commits of both Accel-Sim and GPGPU-Sim to see if this can be fixed.

Also the name is `-gpgpu_shmem_option` instead of `-gpugpu_shmem_option`. Did you make changes related to that or is that a typo? Please also check it.

This option is enabled for [Volta(V100 etc)](https://github.com/accel-sim/gpgpu-sim_distribution/blob/dev/configs/tested-cfgs/SM7_QV100/gpgpusim.config#L116), [Turing(20s)](https://github.com/accel-sim/gpgpu-sim_distribution/blob/dev/configs/tested-cfgs/SM75_RTX2060/gpgpusim.config#L90) and [Ampere(30s)](https://github.com/accel-sim/gpgpu-sim_distribution/blob/dev/configs/tested-cfgs/SM86_RTX3070/gpgpusim.config#L90). These are the config files.

More info on shared memory can be found [here](https://docs.nvidia.com/cuda/volta-tuning-guide/index.html#l1-cache).

**Comment by Rutsow** [comment]
> Hi,
> 
> Which commit you are on for both Accel-Sim and GPGPU-sim? The option is parsed here [gpgpu-sim/gpu-sim.cc](https://github.com/accel-sim/gpgpu-sim_distribution/blob/dev/src/gpgpu-sim/gpu-sim.cc#L331) This option is currently still in the dev branch and only available under the [accel-sim's fork of gpgpu-sim](https://github.com/accel-sim/gpgpu-sim_distribution). Assuming you are using the dev version of Accel-Sim, please try pulling the latest commits of both Accel-Sim and GPGPU-Sim to see if this can be fixed.
> 
> Also the name is `-gpgpu_shmem_option` instead of `-gpugpu_shmem_option`. Did you make changes related to that or is that a typo? Please also check it.
> 
> This option is enabled for [Volta(V100 etc)](https://github.com/accel-sim/gpgpu-sim_distribution/blob/dev/configs/tested-cfgs/SM7_QV100/gpgpusim.config#L116), [Turing(20s)](https://github.com/accel-sim/gpgpu-sim_distribution/blob/dev/configs/tested-cfgs/SM75_RTX2060/gpgpusim.config#L90) and [Ampere(30s)](https://github.com/accel-sim/gpgpu-sim_distribution/blob/dev/configs/tested-cfgs/SM86_RTX3070/gpgpusim.config#L90). These are the config files.
> 
> More info on shared memory can be found [here](https://docs.nvidia.com/cuda/volta-tuning-guide/index.html#l1-cache).
Thank you. The problem really lies in the branch I took. I took the dev-accelwattch branch, it worked. Also, the name is -gpgpu_shmem_option.
